CREATE TABLE osha_inspection_data
	(
	activity_nr int primary key,
	reporting_id int,
	state_flag varchar(6),
	estab_name varchar(128),
	site_address varchar(64),
	site_city varchar(64),
	site_state char(2),
	site_zip int,
	owner_type varchar(32),
	owner_code smallint,
	adv_notice varchar(2),
	safety_hlth varchar(2),
	sic_code smallint,
	naics_code int,
	insp_type char(20),
	insp_scope char(20),
	why_no_insp char(32),
	union_status char(6),
	safety_manuf varchar(10),
	safety_const varchar(10),
	safety_marit varchar(10),
	health_manuf varchar(10),
	health_const varchar(10),
	health_marit varchar(10),
	migrant migrant varchar(10),
	mail_street varchar(64),
	mail_city varchar(64),
	mail_state char(2),
	mail_zip int,
	host_est_key varchar(20),
	nr_in_estab int Null,
	open_date date,
	case_mod_date date Null,
	close_conf_date date Null,
	close_case_date date Null,
	ld_dt TIMESTAMPTZ
	);





	Date date,
	time time,
	Block varchar(64),
	Primary_Type varchar(64),
	Description varchar(64),
	Location_Description varchar(64),
	Arrest boolean,
	Domestic boolean,
	District smallint,
	Ward smallint,
	Community_Area smallint,
	FBI_Code varchar(64),
	Latitude float(8),
	Longitude float(8)
	); 


activity_nr,
reporting_id,
state_flag,
estab_name,
site_address,
site_city,
site_state,
site_zip,
owner_type,
owner_code,
adv_notice,
safety_hlth,
sic_code,
naics_code,
insp_type,
insp_scope,
why_no_insp,
union_status,
safety_manuf,
safety_const,
safety_marit,
health_manuf,
health_const,
health_marit,
migrant,
mail_street,
mail_city,
mail_state,
mail_zip,
host_est_key,
nr_in_estab,
open_date,
case_mod_date,
close_conf_date,
close_case_date,
ld_dt